<?php
/**
 * Use this webservice to get e-class token.
 */

ini_set('display_errors', 1);
ini_set('display_startup_errors', 1);
error_reporting(E_ALL);

$username = isset($_POST['username']) ? $_POST['username'] : die('username is missing');
$password = isset($_POST['password']) ? $_POST['password'] : die('password is missing');

// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/

//get login token
$ch = curl_init();

curl_setopt($ch, CURLOPT_URL, 'https://eclass.aueb.gr/modules/mobile/mlogin.php');
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_POST, 1);
curl_setopt($ch, CURLOPT_POSTFIELDS, "uname=p3170117&pass=22061999j!");

$headers = array();
$headers[] = 'Content-Type: application/x-www-form-urlencoded';
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

$result = curl_exec($ch);
$token = substr($result, strrpos($result, '>') + 1);
if (curl_errno($ch)) {
    echo 'Error:' . curl_error($ch);
}

echo $token;
curl_close($ch);

// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
//get courses
$ch = curl_init();

curl_setopt($ch, CURLOPT_URL, 'https://eclass.aueb.gr/modules/mobile/mcourses.php');
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_POST, 1);
curl_setopt($ch, CURLOPT_POSTFIELDS, "token=$token");

$headers = array();
$headers[] = 'Content-Type: application/x-www-form-urlencoded';
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

$courses = curl_exec($ch);
if (curl_errno($ch)) {
    echo 'Error:' . curl_error($ch);
}
curl_close($ch);

?>
