<?php
/**
 * Use this webservice to get e-class token.
 */

ini_set('display_errors', 1);
ini_set('display_startup_errors', 1);
error_reporting(E_ALL);

$username = isset($_POST['username']) ? $_POST['username'] : die('username is missing');
$password = isset($_POST['password']) ? $_POST['password'] : die('password is missing');
$token = isset($_POST['token']) ? $_POST['token'] : die('token is missing');

// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/

//get login token
$ch = curl_init();

curl_setopt($ch, CURLOPT_URL, 'https://eclass.aueb.gr/modules/mobile/mlogin.php');
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_POST, 1);
curl_setopt($ch, CURLOPT_POSTFIELDS, "uname=p3170117&pass=22061999j!");

$headers = array();
$headers[] = 'Content-Type: application/x-www-form-urlencoded';
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

$result = curl_exec($ch);
$eclass_token = substr($result, strrpos($result, '>') + 1);
if (curl_errno($ch)) {
    echo 'Error:' . curl_error($ch);
}

echo $eclass_token;
curl_close($ch);

// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
//get courses
$ch = curl_init();

curl_setopt($ch, CURLOPT_URL, 'https://eclass.aueb.gr/modules/mobile/mcourses.php');
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_POST, 1);
curl_setopt($ch, CURLOPT_POSTFIELDS, "token=$eclass_token");

$headers = array();
$headers[] = 'Content-Type: application/x-www-form-urlencoded';
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

$courses = curl_exec($ch);
if (curl_errno($ch)) {
    echo 'Error:' . curl_error($ch);
}
curl_close($ch);



//include
include_once '../util/objects/config/Database.php';


//connection to db
$db = new Database();
$conn = $db->getConnection();

//check if user already exists
$email = $username . "@aueb.gr";
$user_id = hashMail($email);
$userExists = userAlreadyExist($user_id, $conn);
if($userExists == 0){
	   //add user to db
        $sql = "INSERT INTO UserInfo (id) VALUES (:user_id)";
        $stmt = $conn->prepare($sql);
        $stmt->bindParam(':user_id', $user_id);
        $stmt->execute();

        //add automatically to groups AUEB and UNIPOLL
        $sql = "INSERT INTO UserToGroup (userId, groupId)	
							VALUEs(:user_id, '1'),	
								  (:user_id, '2') ";
        $stmt = $conn->prepare($sql);
        $stmt->bindParam(':user_id', $user_id);
        $stmt->execute();

        //add token
        addToken($user_id, $token, $conn);
		
		//add to eclass groups
		//addEclassGroups($courses, $conn);
		//addUserToEclassGroups($user_id, $courses, $conn);
	
}else{
	//user alredy exitsts, add token if user has logged from a new device
	$sql = "SELECT * FROM PushNotification WHERE token = :token AND userId = :user_id";
	$stmt = $conn->prepare($sql);
	$stmt->bindParam(':token', $token);
	$stmt->bindParam(':user_id', $user_id);
	$stmt->execute();
	$num = $stmt->rowCount();

	if($num == 0){
		addToken($user_id, $token, $conn);
	}
}

//check if user is super user
$sql = "SELECT isSuperUser FROM UserInfo WHERE id = :user_id";
$stmt = $conn->prepare($sql);
$stmt->bindParam(':user_id', $user_id);
$stmt->execute();
$row = $stmt->fetch(PDO::FETCH_ASSOC);
extract($row);




function userAlreadyExist($user_id, $conn){
    $sql = "SELECT * FROM UserInfo WHERE id = :user_id";
    $stmt = $conn->prepare($sql);
    $stmt->bindParam(':user_id', $user_id);
    $stmt->execute();
    $num = $stmt->rowCount();
	return $num;
	
}

function hashMail($email){
    return sha1($mail);
}

function addToken($user_id, $token, $conn){
    $sql = "INSERT INTO PushNotification (userId, token)	
											VALUES (:user_id, :token)";
    $stmt = $conn->prepare($sql);
	$stmt->bindParam(':token', $token);
    $stmt->bindParam(':user_id', $user_id);
    $stmt->execute();
}


function addEclassGroups($courses, $conn){
	
}

function addUserToEclassGroups($user_id, $courses, $conn){
	
}

?>
